from api_lib import utils as U

CHECKOUT_SESSION_COMPLETE_TABLE = (
    f"{U.COMPANY}-{U.DEVELOPMENT_ENVIRONMENT}-checkout-session-completed"
)

PRODUCT_TABLE_NAME = f"{U.COMPANY}-{U.DEVELOPMENT_ENVIRONMENT}-product"
PRICE_TABLE_NAME = f"{U.COMPANY}-{U.DEVELOPMENT_ENVIRONMENT}-price"
