name: Backend Infrastructure
on:
  workflow_dispatch:
    inputs:
      development_environment:
        default: auto
        required: false
        type: string
      region:
        default: ap-southeast-2
        required: false
        type: string
      mode:
        default: deploy
        required: false
        type: choice
        options:
          - deploy
          - synth
          - destroy
permissions:
  id-token: write
  contents: read
env:
  DEVELOPMENT_ENVIRONMENT: ${{ inputs.development_environment }}
  MODE: ${{ inputs.mode }}
  COMPANY: ${{ vars.COMPANY }}
  DEV_FACEBOOK_CLIENT_ID: ${{ secrets.DEV_FACEBOOK_CLIENT_ID }}
  DEV_FACEBOOK_CLIENT_SECRET: ${{ secrets.DEV_FACEBOOK_CLIENT_SECRET }}
  DEV_STRIPE_SECRET_KEY: ${{ secrets.DEV_STRIPE_SECRET_KEY }}
  DEV_STRIPE_WEBHOOK_SECRET: ${{ secrets.DEV_STRIPE_WEBHOOK_SECRET }}
jobs:
  infrastructure:
    runs-on: ubuntu-20.04
    name: ${{ inputs.mode }}-backend-infrastructure
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEV_AWS_GITHUB_ACTION_ROLE }}
          aws-region: ${{ inputs.region }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Initialize Python Backend
        run: |
          . ./scripts/initialize_backend_python_environment.sh
      - name: Test Infrastructure
        run: |
          . ./scripts/backend_infrastructure_test.sh
      - name: Backend Infrastructure
        run: |
          . ./scripts/backend_infrastructure.sh