name: Deploy Backend Infrastructure
on:
  workflow_dispatch:
    inputs:
      environment:
        default: null
        required: false
        type: string
      region:
        default: ap-southeast-2
        required: false
        type: string
      mode:
        default: deploy
        required: false
        type: choice
        options:
          - deploy
          - destroy
env:
  DEVELOPMENT_ENVIRONMENT: ${{ inputs.environment || github.ref_name == 'master' && 'dev0' || 'dev1'}}
  AWS_DEFAULT_REGION: ${{ inputs.region }}
  DEPLOYMENT_MODE: ${{ inputs.mode }}
  COMPANY: ${{ vars.COMPANY }}
  DEV_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
  DEV_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
  DEV_AWS_SESSION_TOKEN: ${{ secrets.DEV_AWS_SESSION_TOKEN }}
  DEV_FACEBOOK_CLIENT_ID: ${{ secrets.DEV_FACEBOOK_CLIENT_ID }}
jobs:
  deploy-backend-infrastructure:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Initialize Python Backend
        run: |
          . ./scripts/initialize_backend_python_environment.sh
      - name: Set The GitHub Environment
        run: . ./.venv/bin/activate; echo PATH=$PATH >> $GITHUB_ENV
      - name: Deploy Backend Infrastructure
        run: |
          . ./scripts/backend_infrastructure.sh
