name: Deploy Backend Infrastructure
on:
  workflow_dispatch:
    inputs:
      environment:
        default: ${{ github.ref_name == 'master' && 'dev0' || 'dev1' }}
jobs:
  deploy-backend-infrastructure:
    runs-on: ubuntu-20.04
    steps:
      - name: Install AWS CLI
        run: echo "hello world"
