name: Deploy Backend Infrastructure
on:
   workflow_dispatch:
     inputs:
       environment:
         default: dev0
jobs:
  bash-example:
    runs-on: ubuntu-20.04
    environment: Development
    steps:
      - name: Print
        run: |
          echo "the development environment: $DEVELOPMENT_ENVIRONMENT"